name: CI/CD - API REST

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: Pruebas y cobertura
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v7

      - name: Configurar Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "22"
          cache: "npm"

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar pruebas y cobertura
        run: npm run test:coverage

  docker:
    name: Construir y publicar imagen Docker
    runs-on: ubuntu-latest
    needs: test

    # Solo publicar imagen cuando sea push a main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v7

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y publicar imagen
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            pao1606/webapp-api-node:latest
            pao1606/webapp-api-node:${{ github.sha }}